# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(481, 260)
        self.tab_widget = QtWidgets.QTabWidget(Form)
        self.tab_widget.setGeometry(QtCore.QRect(0, -10, 481, 291))
        self.tab_widget.setTabBarAutoHide(True)
        self.tab_widget.setObjectName("tab_widget")
        self.add_tab = QtWidgets.QWidget()
        self.add_tab.setObjectName("add_tab")
        self.description_line = QtWidgets.QLineEdit(self.add_tab)
        self.description_line.setGeometry(QtCore.QRect(100, 120, 371, 20))
        self.description_line.setObjectName("description_line")
        self.price_line = QtWidgets.QLineEdit(self.add_tab)
        self.price_line.setGeometry(QtCore.QRect(100, 150, 371, 20))
        self.price_line.setObjectName("price_line")
        self.volume_line = QtWidgets.QLineEdit(self.add_tab)
        self.volume_line.setGeometry(QtCore.QRect(100, 180, 371, 20))
        self.volume_line.setObjectName("volume_line")
        self.add_btn = QtWidgets.QPushButton(self.add_tab)
        self.add_btn.setGeometry(QtCore.QRect(390, 220, 75, 23))
        self.add_btn.setObjectName("add_btn")
        self.sort_box = QtWidgets.QComboBox(self.add_tab)
        self.sort_box.setGeometry(QtCore.QRect(100, 20, 371, 22))
        self.sort_box.setObjectName("sort_box")
        self.degree_box = QtWidgets.QComboBox(self.add_tab)
        self.degree_box.setGeometry(QtCore.QRect(100, 50, 371, 22))
        self.degree_box.setObjectName("degree_box")
        self.type_box = QtWidgets.QComboBox(self.add_tab)
        self.type_box.setGeometry(QtCore.QRect(100, 80, 371, 22))
        self.type_box.setObjectName("type_box")
        self.label_7 = QtWidgets.QLabel(self.add_tab)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.add_tab)
        self.label_8.setGeometry(QtCore.QRect(10, 150, 61, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.add_tab)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.add_tab)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.add_tab)
        self.label_11.setGeometry(QtCore.QRect(10, 120, 61, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.add_tab)
        self.label_12.setGeometry(QtCore.QRect(10, 180, 61, 16))
        self.label_12.setObjectName("label_12")
        self.tab_widget.addTab(self.add_tab, "")
        self.change_tab = QtWidgets.QWidget()
        self.change_tab.setObjectName("change_tab")
        self.degree_box_edit = QtWidgets.QComboBox(self.change_tab)
        self.degree_box_edit.setGeometry(QtCore.QRect(100, 50, 371, 22))
        self.degree_box_edit.setObjectName("degree_box_edit")
        self.volume_line_edit = QtWidgets.QLineEdit(self.change_tab)
        self.volume_line_edit.setGeometry(QtCore.QRect(100, 180, 371, 20))
        self.volume_line_edit.setObjectName("volume_line_edit")
        self.description_line_edit = QtWidgets.QLineEdit(self.change_tab)
        self.description_line_edit.setGeometry(QtCore.QRect(100, 120, 371, 20))
        self.description_line_edit.setObjectName("description_line_edit")
        self.edit_btn = QtWidgets.QPushButton(self.change_tab)
        self.edit_btn.setGeometry(QtCore.QRect(390, 220, 75, 23))
        self.edit_btn.setObjectName("edit_btn")
        self.price_line_edit = QtWidgets.QLineEdit(self.change_tab)
        self.price_line_edit.setGeometry(QtCore.QRect(100, 150, 371, 20))
        self.price_line_edit.setObjectName("price_line_edit")
        self.sort_box_edit = QtWidgets.QComboBox(self.change_tab)
        self.sort_box_edit.setGeometry(QtCore.QRect(100, 20, 371, 22))
        self.sort_box_edit.setObjectName("sort_box_edit")
        self.type_box_edit = QtWidgets.QComboBox(self.change_tab)
        self.type_box_edit.setGeometry(QtCore.QRect(100, 80, 371, 22))
        self.type_box_edit.setObjectName("type_box_edit")
        self.label = QtWidgets.QLabel(self.change_tab)
        self.label.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.change_tab)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.change_tab)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.change_tab)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.change_tab)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.change_tab)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 61, 16))
        self.label_6.setObjectName("label_6")
        self.tab_widget.addTab(self.change_tab, "")

        self.retranslateUi(Form)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.description_line.setPlaceholderText(_translate("Form", "Введите описание"))
        self.price_line.setPlaceholderText(_translate("Form", "Введите цену"))
        self.volume_line.setPlaceholderText(_translate("Form", "Введите объём"))
        self.add_btn.setText(_translate("Form", "Добавить"))
        self.label_7.setText(_translate("Form", "Степень прожарки"))
        self.label_8.setText(_translate("Form", "Цена"))
        self.label_9.setText(_translate("Form", "Сорт"))
        self.label_10.setText(_translate("Form", "Тип"))
        self.label_11.setText(_translate("Form", "Описание"))
        self.label_12.setText(_translate("Form", "Объём"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.add_tab), _translate("Form", "Добавить кофе"))
        self.volume_line_edit.setPlaceholderText(_translate("Form", "Введите объём"))
        self.description_line_edit.setPlaceholderText(_translate("Form", "Введите описание"))
        self.edit_btn.setText(_translate("Form", "Сохранить"))
        self.price_line_edit.setPlaceholderText(_translate("Form", "Введите цену"))
        self.label.setText(_translate("Form", "Сорт"))
        self.label_2.setText(_translate("Form", "Степень прожарки"))
        self.label_3.setText(_translate("Form", "Тип"))
        self.label_4.setText(_translate("Form", "Описание"))
        self.label_5.setText(_translate("Form", "Цена"))
        self.label_6.setText(_translate("Form", "Объём"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.change_tab), _translate("Form", "Изменить кофе"))
